### ISSUE TITLE
Dont install

### ISSUE THREAD

**Issue by AndreyS96** [rolfjoseph/2017-OpenWebSoccer#1]
Hello i download your new WebSoccer
But he dont install
ERR_TOO_MANY_REDIRECTS

**Comment by AndreyS96** [comment]
All time http://pro-m-f.ru/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install

**Comment by rolfjoseph** [comment]
"Diese Version ist zuvor noch nie veröffentlicht worden, da es sich um eine Developer-Version handelt. Es können also einige kleine Fehler enthalten sein."

The 2017-OpenWebSoccer ist only the last stand of development and not completly bugfree. There isn´t an folder install inside. You have to install the version of 2016.

To try the version 2017, you need the config.inc.php at the folder generated from the version 2016.

**Comment by AndreyS96** [comment]
I have download the 2016 version, and then on top of this version to set 2017?

**Comment by AndreyS96** [comment]
Where you can take Russian language for Manager

**Comment by rolfjoseph** [comment]
I have download the 2016 version, and then on top of this version to set 2017?

This should work.


Where you can take Russian language for Manager


There is no Russian translation


At the version 2017 I have summarized all the language parts from the modules in a few files, so that a translation is easier. At the directory core the .xml files can be found.

It is not until the end of 2018 that a rudimentary translation into other languages ​​is planned.

**Comment by AndreyS96** [comment]
And how to translate into Russian, I just do not understand the codes

**Comment by rolfjoseph** [comment]
On of the files -> 2017-OpenWebSoccer/websoccer/modules/core/messages_de.xml

from <message id='allaktivities_navlabel'>Alle User Aktivitäten</message>
to <message id='allaktivities_navlabel'>Усе дзеянні карыстальніка</message>

I hope this is the correct translation, it´s translatet by google translate.

**Comment by AndreyS96** [comment]
Please add more language

**Comment by AndreyS96** [comment]
Is not installed. That's what gives 
![1](https://user-images.githubusercontent.com/36029669/35674956-685a8fd8-0757-11e8-988c-05914564e499.jpg)

**Comment by rolfjoseph** [comment]
Oh, the hosting has regressive server settings. For each folder, the folder rights must be set to 755 with the ftp program.

These settings form the hoster aren´t normaly ! We habe here no problems with this.

**Comment by AndreyS96** [comment]
I will try to write to the hoster

**Comment by AndreyS96** [comment]
My hoster changed everything to 755, but still nothing has changed

**Comment by AndreyS96** [comment]
Hosting responded 
On this issue, we recommend to contact developers of the script and to clarify other possible causes of errors. 
If we need help, please do.

**Comment by rolfjoseph** [comment]
Look at https://manager.topligclub.de/, it works fine.


You must upload the websoccer directory as a whole and not just the content.

After each deletion of directories, the newly uploaded directories are always new to set the write-control.
I could only see the installation once, which was probably deleted afterwards!

I can´t access http://pro-m-f.ru/websoccer/build.txt, so you haven´t install it.

Get a try from the original https://github.com/ihofmann/open-websoccer

**Comment by AndreyS96** [comment]
You can helpme i install this https://github.com/ihofmann/open-websoccer. And dont connect to admincenter.
All time write You need to log in!
Please provide your credentials below.
But my password is right

**Comment by rolfjoseph** [comment]
Upload now https://github.com/rolfjoseph/2014-OpenWebSoccer-Sim
and overwrite your installation.

You have PHP 7.0.27, but this old version work only with PHP 5.6 !

With my version 2014 you can acces it unter PHP 7.0.x

**Comment by AndreyS96** [comment]
Ok

**Comment by AndreyS96** [comment]
Close!!
