### ISSUE TITLE
Games Season

### ISSUE THREAD

**Issue by AndreyS96** [rolfjoseph/2017-OpenWebSoccer#2]
Hi. How do I do so in the day of the season was played 1 game and there are a few 2-3

**Comment by rolfjoseph** [comment]
So, you want to do 3 games a day?

You need an add-on. There you can move the games.

But I go to work, I'll get back to you afterwards.

**Comment by AndreyS96** [comment]
Well, I'll wait 
I do wish that it was possible to choose how many games per day you can do

**Comment by rolfjoseph** [comment]
Look at https://github.com/rolfjoseph/WebsoccerExtension

You have to move every playday to another day/time.
